#define SIZE_FLOAT_32_T 4

#define MAG_START 0
#define MAG_COUNT 6

#define ACCEL_START (MAG_START + SIZE_FLOAT_32_T * MAG_COUNT)
#define ACCEL_COUNT 6

#define ROLL_START (ACCEL_START + SIZE_FLOAT_32_T * ACCEL_COUNT)
#define ROLL_COUNT 3

#define PITCH_START (ROLL_START + SIZE_FLOAT_32_T * ROLL_COUNT)
#define PITCH_COUNT 3

#define THROTTLE_START (PITCH_START + SIZE_FLOAT_32_T * PITCH_COUNT)
#define THROTTLE_COUNT 3

#define YAW_START (THROTTLE_START + SIZE_FLOAT_32_T * THROTTLE_COUNT)
#define YAW_COUNT 3

#define TOP_LEFT_SWITCH_START (YAW_START + SIZE_FLOAT_32_T * YAW_COUNT)
#define TOP_LEFT_SWITCH_COUNT 3

#define TOP_RIGHT_SWITCH_START (TOP_LEFT_SWITCH_START + SIZE_FLOAT_32_T * TOP_LEFT_SWITCH_COUNT)
#define TOP_RIGHT_SWITCH_COUNT 3

#define LAST_CHANNEL_START (TOP_RIGHT_SWITCH_START + SIZE_FLOAT_32_T * TOP_RIGHT_SWITCH_COUNT)
#define LAST_CHANNEL_COUNT 3